### PR TITLE
CTONET-2898 SNO fixes

### LINKED ISSUE #18: Create empty ManagedClusterInfo in SNO base
ManagedClusterInfo is created by ACM behind the scene.
Argo CD keeps syncing this object, a possible solution is to create an empty object so Argo will know it.

This should be the same as [in 3-node](https://github.com/redhat-partner-solutions/vse-ocp-bases/blob/main/base/3-node/managed-cluster-info.yaml)

### LINKED ISSUE #19: The rootDeviceHints need to be under spec
The rootDeviceHints need to be under spec and not in the bmc.
[sno bmh file](https://github.com/redhat-partner-solutions/vse-ocp-bases/blob/main/base/sno/bmh.yaml)

### LINKED ISSUE #20: SNO Klusterletaddon name patch should be cluster name
The cluster name is incorrect.
Need to change the overlay sno sample [klusterletaddon-patch.yaml](https://github.com/redhat-partner-solutions/vse-ocp-bases/blob/main/overlay/sno/patches/klusterletaddon-patch.yaml)  from klusterletaddonconfig-rna4 to rna4

### PR DESCRIPTION
**Pull request by natifridman**
Fix #18 
Fix #20
Fix #19

### CODE REVIEW

**Comment by natifridman** [comment]
Please don't merge yet, I would like to use this PR to test the Jira integration

**Comment by natifridman** [comment]
Ready for review

**Comment by halleelyasaf** [comment]
Looking good.
Do you want me to try to deploy that changes before you merge?

**Comment by natifridman** [comment]
> Looking good. Do you want me to try to deploy that changes before you merge?

@halleelyasaf If you have some time and resources for this - sure
I based this on the changes you did in your environment

**Comment by halleelyasaf** [comment]
I will deploy on Sunday SNO cluster and 5-Node and use this changes

**Review by nocturnalastro — APPROVED** [review]

**Comment by halleelyasaf** [comment]
@natifridman I tested that yesterday and it work thanks

**Pull request merged**
