### PR TITLE
CTONET-2899 Removing SNO nmstate feilds which is causing errors in merge

### LINKED ISSUE #17: Change SNO nmstate name and namespace
Currently set for rna4 which isn't user-friendly when creating a new overlay, since it must use the same name for the kustomize strategic merge

### PR DESCRIPTION
**Pull request by nocturnalastro**
Fix #17

### CODE REVIEW

**Review by natifridman — COMMENTED** [review]
We need to `cluster-name` label for `ClusterSet` object.
Also, if you are updating the name you probably need to update the overlay as well for using the `PatchesStrategicMerge`

**Comment by nocturnalastro** [comment]
> We need to `cluster-name` label for `ClusterSet` object. Also, if you are updating the name you probably need to update the overlay as well for using the `PatchesStrategicMerge`

I updated the overlay and the `cluster-name` is added in the overlay already.

**Review by natifridman — APPROVED** [review]
LGTM. Thanks for that!

**Comment by natifridman** [comment]
Merging this will need to make the changes also in `vse-carslab-hub` repo. Suggesting to open a PR for these changes there as well

**Comment by nocturnalastro** [comment]
> Merging this will need to make the changes also in `vse-carslab-hub` repo. Suggesting to open a PR for these changes there as well

What changes are required in the hub repo? I don't see any of them using SNO ATM.

**Comment by natifridman** [comment]
> What changes are required in the hub repo? I don't see any of them using SNO ATM.

Correct, I thought there was a SNO cluster over there. So ready for merge

**Pull request merged**
